A=set()
B=set()
n1=int(input("Enter the size of set A"))
print("Enter the details of set A")
for i in range(0,n1):
    A.add(input(""))
n2=int(input("Enter the size of set B"))
print("Enter the details of set B")
for i in range(0,n2):
    B.add(input(""))
print("The set A is {} The set B is {}".format(A,B))
print("The union is {}".format(A | B))
print("The Intersection is {}".format(A & B))
print("The Set difference is {}".format(A - B))
print("The Symmetric difference is {}".format(A ^ B))
